In [50]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [8, 1], [7, 2], [5, 4], [6, 3], [1, 4], [2, 3]])
y = np.array([0, 0, 1, 1, 2, 2, 3, 3, 4 ,4])
sss = StratifiedShuffleSplit(n_splits=2, test_size=0.5, random_state=0)

print(sss, sss.get_n_splits(X, y))       


StratifiedShuffleSplit(n_splits=2, random_state=0, test_size=0.5,
            train_size=None) 2


In [51]:
for train_index, test_index in sss.split(X, y):
    print("\n>TRAIN:", train_index, ">TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)
    print("\n", X_test)
    print("\n", y_train, y_test)


>TRAIN: [1 4 2 8 7] >TEST: [3 6 9 0 5]
[[3 4]
 [8 1]
 [1 2]
 [1 4]
 [6 3]]

 [[3 4]
 [5 4]
 [2 3]
 [1 2]
 [7 2]]

 [0 2 1 4 3] [1 3 4 0 2]

>TRAIN: [9 5 6 3 1] >TEST: [4 7 8 2 0]
[[2 3]
 [7 2]
 [5 4]
 [3 4]
 [3 4]]

 [[8 1]
 [6 3]
 [1 4]
 [1 2]
 [1 2]]

 [4 2 3 1 0] [2 3 4 1 0]
