In [1]:
import pickle
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pickle
from collections import deque
import glob
import imageio
# Import everything needed to edit/save/watch video clips
from moviepy.editor import VideoFileClip
from IPython.display import HTML
%matplotlib inline


In [2]:
corners = np.float32([[190,720],[589,457],[698,457],[1145,720]])
new_top_left=np.array([corners[0,0],0])
new_top_right=np.array([corners[3,0],0])
offset=[150,0]
print(new_top_left,new_top_right)

[ 190.    0.] [ 1145.     0.]


In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

nonzero = a.nonzero()
nonzeroy = np.array(nonzero[0])
nonzerox = np.array(nonzero[1])
print(nonzeroy,nonzerox)
np.nonzero(a > 3)    

[0 0 0 1 1 1 2 2 2] [0 1 2 0 1 2 0 1 2]


(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [9]:
(a > 3).nonzero()[0]

array([1, 1, 1, 2, 2, 2])

In [14]:
nonzerox[(a > 3).nonzero()[0]]

array([1, 1, 1, 2, 2, 2])