In [1]:
import pickle
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pickle
from collections import deque
import glob
import imageio
# Import everything needed to edit/save/watch video clips
from moviepy.editor import VideoFileClip
from IPython.display import HTML
%matplotlib inline


In [2]:
corners = np.float32([[190,720],[589,457],[698,457],[1145,720]])
new_top_left=np.array([corners[0,0],0])
new_top_right=np.array([corners[3,0],0])
offset=[150,0]
print(new_top_left,new_top_right)

[ 190.    0.] [ 1145.     0.]


In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

nonzero = a.nonzero()
nonzeroy = np.array(nonzero[0])
nonzerox = np.array(nonzero[1])
print(nonzeroy,nonzerox)
np.nonzero(a > 3)    

[0 0 0 1 1 1 2 2 2] [0 1 2 0 1 2 0 1 2]


(array([1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2]))

In [4]:
(a > 3).nonzero()[0]

array([1, 1, 1, 2, 2, 2])

In [5]:
nonzerox[(a > 3).nonzero()[0]]

array([1, 1, 1, 2, 2, 2])

In [6]:
#Suppose your have this array:
myarray = np.array([[0, 20, 0],[30, 100, 40], [0,50,0]])
print(myarray)

[[  0  20   0]
 [ 30 100  40]
 [  0  50   0]]


In [8]:
#Step 1: Non Zero indices

nonzero_myarray = myarray.nonzero()
print(nonzero_myarray)

nonzerox = nonzero_myarray[1]
nonzeroy = nonzero_myarray[0]

(array([0, 1, 1, 1, 2]), array([1, 0, 1, 2, 1]))


In [9]:
#Step 2: Find Target indices

#So the non-zero y indices for the our search criteria (non zero values excluding 1st row):
print(nonzeroy >= 1)

#So the non-zero x indices for the our search criteria (non zero values excluding 1st column):
print(nonzerox >= 1)

#Combining these 2 criteria we get:
good_indices = ((nonzeroy >= 1) & (nonzerox >= 1))
print(good_indices)

good_indices = good_indices.nonzero()[0]
print(good_indices)

[False  True  True  True  True]
[ True False  True  True  True]
[False False  True  True  True]
[2 3 4]


In [10]:
#Step 3: Find the target y & x indices

good_x = nonzerox[good_indices]
print(good_x)

good_y = nonzeroy[good_indices]
print(good_y)


[1 2 1]
[1 1 2]


In [11]:
#Step 4: Set the value of these indices to -1

myarray[good_y, good_x] = -1

print(myarray)

[[ 0 20  0]
 [30 -1 -1]
 [ 0 -1  0]]
